# Generated by Django 4.1.4 on 2022-12-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=8, verbose_name='Номер кошелька')),
                ('type', models.CharField(choices=[('VISA', 'VISA'), ('MASTERCARD', 'MASTERCARD')], max_length=10, verbose_name='Тип кошелька')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('RUB', 'RUB')], max_length=3, verbose_name='Валюта')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='wallet.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Комиссия')),
                ('status', models.CharField(choices=[('True', 'PAID'), ('False', 'FAILED')], max_length=15, verbose_name='Тип кошелька')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='wallet.wallet', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='wallet.wallet', verbose_name='Отправитель')),
            ],
        ),
    ]
