# Generated by Django 4.1.4 on 2022-12-13 11:13

from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=wallet.models.generate_name, max_length=9)),
                ('type', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard')], default='Visa', max_length=15, verbose_name='Тип кошелька')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUB', 'Ruble')], default='USD', max_length=4, verbose_name='Валюта')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.user', verbose_name='Владелец карты')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Комиссия')),
                ('status', models.CharField(choices=[('True', 'PAID'), ('False', 'FAILED')], default='FAILED', max_length=15, verbose_name='Тип кошелька')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='wallet.wallet', verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='wallet.wallet', verbose_name='Отправитель')),
            ],
        ),
    ]
