# Generated by Django 4.1.4 on 2022-12-13 13:09

from django.db import migrations, models
import django.db.models.deletion
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='wallet.wallet', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='wallet.wallet', verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default=wallet.models.generate_name, max_length=9, verbose_name='Номер кошелька'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='wallet.user', verbose_name='Владелец карты'),
        ),
    ]
