# Generated by Django 4.1.4 on 2022-12-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(default=None, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', unique=True, verbose_name='Владелец'),
        ),
    ]
